# Generated by Django 4.1.4 on 2023-01-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_illustrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="age",
            field=models.IntegerField(
                blank=True, help_text="Add an appropriate age for this book.", null=True
            ),
        ),
    ]
