# Generated by Django 4.1.4 on 2023-01-04 23:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_book_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
