# Generated by Django 4.1.4 on 2023-01-05 00:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=markdownx.models.MarkdownxField(
                help_text="Use markdown for formatting"
            ),
        ),
    ]
