# Generated by Django 4.1.4 on 2023-01-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="goodreads",
            field=models.URLField(
                blank=True, help_text="Add link to goodreads page", null=True
            ),
        ),
    ]
