# Generated by Django 4.1.4 on 2023-01-18 06:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("book", "0007_book_goodreads"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="categories",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
