# Generated by Django 4.1.4 on 2023-02-12 05:35

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_tagulous_book_categories_book_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                help_text="Enter a comma-separated tag string",
                to="book.tagulous_book_categories",
            ),
        ),
    ]
