# Generated by Django 4.1.4 on 2023-02-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="display",
            field=models.BooleanField(
                default=True, help_text="Uncheck to hide on the site."
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
    ]
