# Generated by Django 4.1.4 on 2023-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0011_book_display_alter_book_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=144)),
                ("book", models.ManyToManyField(to="book.book")),
            ],
        ),
    ]
